version: '3.9'

services:
  content-management:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/content_management
      - PULSAR_SERVICE_URL=pulsar://pulsar:6650
      - PULSAR_ADMIN_URL=http://pulsar:8080
      - FLASK_ENV=development
    depends_on:
      - postgres
      - pulsar
      - pulsar-init
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=content_management
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pulsar:
    image: apachepulsar/pulsar:4.1.0
    command: ["bin/pulsar", "standalone"]
    restart: unless-stopped
    ports:
      - "6650:6650"
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/admin/v2/brokers/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

  pulsar-init:
    image: apachepulsar/pulsar:4.1.0
    depends_on:
      pulsar:
        condition: service_healthy
    environment:
      PULSAR_ADMIN_URL: http://pulsar:8080
    volumes:
      - ./scripts/init-pulsar.sh:/init-pulsar.sh:ro
    command: ["sh", "/init-pulsar.sh"]

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.4.0
    ports:
      - "9528:9527"
      - "7751:7750"
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
    command: ["sh", "-c", "bin/pulsar-manager"]
    depends_on:
      - pulsar

volumes:
  postgres_data:
  pulsar_data:
